Incomplete/needs help/working
csci-2479/tabletop-nerds pull request #90
Opened 2021-11-13 01:30 UTC by sarahdactylrex

Hey guys, I'm still having some trouble with the seeders but wanted to commit an update. I keep getting an error when I try to add the publisher foreign id on the game table, in the form of 'does not have a default value'. I tried adding it to the protected fillable in the game model and changing publishers to publisher all over. If I change our database config strict to false I get an integrity constraint violation parent/child even though the foreign key is nullable. It seems absurd that a table is giving me this much trouble, but here we are. I can't seem to find what I'm doing wrong with the publisher integration while the category seed/migr works fine, it's driving me bonkers but I'll look at this again over the weekend, if anyone can point out the error I would surely appreciate the assist! Thanks!

Resolves #81 and #87

2021-11-13 18:35 UTC, oldskoolfan commented
@sarahdactylrex don't feel bad, I had to re-read a lot of the Eloquent relationship docs to get this working, particularly this section: https://laravel.com/docs/8.x/eloquent-relationships#updating-many-to-many-relationships

See my commit re: changing a couple of columns and model properties. Good job on this!

2021-11-13 18:38 UTC, oldskoolfan requested changes

2021-11-13 18:38 UTC, oldskoolfan commented on database/seeders/GameSeeder.php
> +            // $econCat = Category::where('code', 'ECON')->first()->games()->save();
just clean up the commented code and we can merge this

2021-11-13 23:23 UTC, sarahdactylrex commented
Thanks for the help on this one, I get the relationship a little better now.

2021-11-14 04:09 UTC, oldskoolfan approved these changes

2021-11-14 04:10 UTC, merged