Game Rating Feature
csci-2479/tabletop-nerds pull request #92
Opened 2021-11-15 22:31 UTC by ctruong1

Hi everyone. I'm kinda lost on how to finish up #79. For some reason I just cant figure out how to get the form data to summit to the database/game_user table. I've tried doing this a few different ways but still cant get it to work. Helps pls :( any suggestions on how I should do this??

2021-11-16 02:49 UTC, dshea18 commented
Hey Colin @ctruong1 , I'm taking a look at this now to help out.  FYI, Sarah (@sarahdactylrex ) and Andrew (@oldskoolfan), I'm going to create a branch to build out some additional code. If anyone else has started on this let me know.

Thanks,
Danny

2021-11-16 04:33 UTC, oldskoolfan commented
There's some sections of the Eloquent documentation worth looking at:
https://laravel.com/docs/8.x/eloquent-relationships#retrieving-intermediate-table-columns
https://laravel.com/docs/8.x/eloquent-relationships#customizing-the-pivot-attribute-name
https://laravel.com/docs/8.x/eloquent-relationships#defining-custom-intermediate-table-models

Let me know if I can help with this, curious to see where you get @dshea18

2021-11-16 18:35 UTC, dshea18 requested changes
Hey Colin,

I just sent over a pull request for additional things that would be needed to get this feature to work. Take a look and let me know what you think and see if it helps out.

V/R,
Danny

2021-11-16 19:23 UTC, sarahdactylrex approved these changes
Danny, dude, this looks amazing! I barely got a minute to look over the initial commit and it looks like you've solved it! Cool beans!

2021-11-16 19:35 UTC, sarahdactylrex submitted a review, later dismissed

2021-11-16 19:58 UTC, ctruong1 reviewed
Everything looks great!!! Thanks again for your help @dshea18! :)

2021-11-17 01:49 UTC, oldskoolfan requested changes
just some minor suggestions, thank you for helping out with this @dshea18 !

2021-11-17 01:49 UTC, oldskoolfan commented on app/Http/Controllers/UserController.php
> +        $userReview = $this->userService->submitGameReview($validatedInput['game_id'],$user_id,$validatedInput['game_rating'],$validatedInput['text_review']);
can we wrap this so the line isn't so long? makes for better readability

2021-11-17 01:49 UTC, oldskoolfan commented on app/Http/Requests/UserGameReviewPost.php
> +class UserGameReviewPost extends FormRequest
Nice!

2021-11-17 01:49 UTC, oldskoolfan commented on app/Repositories/GameRepository.php
>  }
needs newline at EOF

2021-11-17 01:49 UTC, oldskoolfan commented on app/Models/Reviews.php
> +class Reviews extends Model
I think the many-to-many linking tables need to extend the pivot class based on what I saw here: https://laravel.com/docs/8.x/eloquent-relationships#defining-custom-intermediate-table-models

2021-11-17 01:49 UTC, oldskoolfan commented on app/Repositories/UserRepository.php
>  }
needs newline at EOF

2021-11-17 01:49 UTC, oldskoolfan commented on app/Services/GameService.php
>  }
needs newline at EOF

2021-11-17 01:49 UTC, oldskoolfan commented on app/Services/UserService.php
>  }
needs newline at EOF

2021-11-17 01:49 UTC, oldskoolfan commented on app/Services/UserService.php
> +        $returnedReview = $submittedReview;
why not just `return $this->userRepository->InsertGameReview($game_id, $user_id, $game_rating, $text_review);`

2021-11-17 01:49 UTC, oldskoolfan commented on resources/views/gameView.blade.php
> +    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
remove commented code

2021-11-17 01:49 UTC, oldskoolfan commented on routes/web.php
> +// Route::post('/gameView',function(){
remove commented code

2021-11-17 04:47 UTC, ctruong1 commented
Hi everyone, I made some new commits with a few updates hope I didn't mess anything up

2021-11-17 23:19 UTC, oldskoolfan submitted a review, later dismissed
looks good!

2021-11-18 00:44 UTC, sarahdactylrex approved these changes
Excellent work!

2021-11-18 02:23 UTC, merged

2021-11-18 02:23 UTC, dshea18 approved these changes